/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface CloudflareEnv ./cloudflare-env.d.ts` (hash: 20042e1e53eed4f5933c507a73b9d3a4)
declare namespace Cloudflare {
  interface Env {
    NEXTJS_ENV: string;
    ASSETS: Fetcher;
  }
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<Pick<Cloudflare.Env, "NEXTJS_ENV">> {}
}
